name: Deploy to BACKEND on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook on BACKEND
        run: |
          curl -i -X POST \
            -H "Content-Type: application/json" \
            -H "X-Deploy-Secret: ${{ secrets.DEPLOY_SECRET }}" \
            -d '{"event":"push"}' \
            http://137.184.13.214:9000/hooks/deploy
